from sqlalchemy import Column, Integer, String, Float, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from datetime import datetime
from app.database import Base

class Candidate(Base):
    __tablename__ = "candidates"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=True)
    email = Column(String, nullable=True)
    skills = Column(Text, nullable=True)  # JSON-encoded list of skills
    experience_level = Column(String, nullable=True)
    domain_exposure = Column(Text, nullable=True)  # JSON-encoded list
    parsed_text = Column(Text, nullable=True)  # Full parsed resume text
    created_at = Column(DateTime, default=datetime.utcnow)

    sessions = relationship("InterviewSession", back_populates="candidate")


class InterviewSession(Base):
    __tablename__ = "interview_sessions"

    id = Column(String, primary_key=True, index=True)  # Unique session UUID
    candidate_id = Column(Integer, ForeignKey("candidates.id"))
    selected_role = Column(String, nullable=False)  # e.g., "ai_ml_engineer", "backend_engineer", "data_scientist"
    status = Column(String, default="started")  # started, in_progress, completed
    created_at = Column(DateTime, default=datetime.utcnow)
    finished_at = Column(DateTime, nullable=True)
    overall_score = Column(Float, nullable=True)
    summary_report = Column(Text, nullable=True)  # JSON or Markdown report of strengths, weaknesses, etc.

    candidate = relationship("Candidate", back_populates="sessions")
    questions = relationship("InterviewQuestion", back_populates="session", cascade="all, delete-orphan")


class InterviewQuestion(Base):
    __tablename__ = "interview_questions"

    id = Column(Integer, primary_key=True, index=True)
    session_id = Column(String, ForeignKey("interview_sessions.id"))
    question_text = Column(Text, nullable=False)
    context_retrieved = Column(Text, nullable=True)  # JSON string listing RAG source chunks for traceability
    correct_answer_guideline = Column(Text, nullable=True)  # Evaluation criteria generated by LLM
    difficulty = Column(String, nullable=True)  # beginner, intermediate, advanced
    candidate_answer = Column(Text, nullable=True)
    evaluation_feedback = Column(Text, nullable=True)  # LLM grading explanation
    score = Column(Float, nullable=True)  # Score from 1 to 10
    created_at = Column(DateTime, default=datetime.utcnow)

    session = relationship("InterviewSession", back_populates="questions")


class RAGChunk(Base):
    __tablename__ = "rag_chunks"

    id = Column(Integer, primary_key=True, index=True)
    role = Column(String, index=True, nullable=False)  # ai_ml_engineer, backend_engineer, data_scientist
    document_name = Column(String, nullable=False)
    chunk_text = Column(Text, nullable=False)
    embedding_json = Column(Text, nullable=False)  # JSON representation of the float vector
    created_at = Column(DateTime, default=datetime.utcnow)
